language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy

# command to install dependencies
install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libxml2-utils
    - pip install tox

script:
    - printf "[build_ext]\nportage-ext-modules=true" >> setup.cfg
    - ./setup.py install --root=/tmp/install-root
    - if [[ ${TRAVIS_PYTHON_VERSION} == ?.? ]]; then
        tox -e py${TRAVIS_PYTHON_VERSION/./};
      else
        tox -e ${TRAVIS_PYTHON_VERSION};
      fi
